services:
 accounts:
  image: yogeshwar100/accounts:s04
  container_name: accounts_ms
  ports:
  - 8080:8080
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
  - eazybank

 loans:
  image: yogeshwar100/loans:s04
  container_name: loans_ms
  ports:
  - 8090:8090
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
  - eazybank
  
          
 cards:
  image: yogeshwar100/cards:s04
  container_name: cards_ms
  ports:
  - 9000:9000
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
  - eazybank

networks:
 eazybank:
  driver: "bridge"
  